# Site settings
title: Zhiye Tang
description: 'Curriculum Vitae'
url: 'https://zhiyetang.github.io'
baseurl: ''
profilepic: '/images/zhiyetang.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Zhiye Tang'
  email: zhiyetang2022@foxmail.com
  github_username:  ZhiyeTang

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
